version: "3.9"
services:
  laravel:
    build:
      context: ./
      args:
        user: "$USER"
        uid: 1000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    working_dir: /app
    command: bash -c "composer install ; php artisan serve --host 0.0.0.0"
  mysql:
    image: mysql:5.7.33
    ports:
      - 3306:3306
    environment:
<<<<<<< HEAD
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: fabricio
      MYSQL_PASSWORD: c843d31001
      MYSQL_DATABASE: companybook
=======
      MYSQL_DATABASE: dbthik
      MYSQL_USER: dbthinkuser
      MYSQL_PASSWORD: dbthinkpass
      MYSQL_ROOT_PASSWORD: rootpass
>>>>>>> 62941f0ac5d29cdac3a970b0241e978e97b25174
    volumes:
      - ./docker/backup.sql:/docker-entrypoint-initdb.d/backup.sql
