version: "3.9"
services:
  laravel:
    build:
      context: ./
      args:
        user: "$USER"
        uid: 1000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    working_dir: /app
    command: bash -c "composer install ; php artisan serve --host 0.0.0.0"
