name: Git Pull to EC2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Git Pull
        run: |
          echo "${{ secrets.EC2_THINK_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking=no" -i private_key.pem ${{ secrets.EC2_THINK_USER }}@${{ secrets.EC2_THINK_HOST }} 'cd /var/www/think-backend && git config --global --add safe.directory /var/www/think-backend && sudo git pull'
          sudo chown -R www-data: storage
          sudo chmod -R 755 storage
          sudo chown -R www-data:www-data /var/www/think-backend/bootstrap/cache
          sudo chmod -R 775 /var/www/think-backend/bootstrap/cache
          sudo service apache2 restart
          rm private_key.pem